### ISSUE TITLE
Pool Owner - serviceable zip codes

### ISSUE THREAD

**Issue by christa23** [Rowboatllc/poolservice#1]
Please update serviceable zip codes with the attached list.
[Serviceable zip codes.xlsx](https://github.com/Rowboatllc/poolservice/files/981779/Serviceable.zip.codes.xlsx)

**Comment by maiquynh** [comment]
@christa23: Due to some technical issue we face, we aren't able to verify Zipcodes entered by Pool Service Company base on your list like our previous estimation like below:
![image](https://cloud.githubusercontent.com/assets/21021038/25842717/29836d1c-34cf-11e7-9aa9-fa7cf3c8de8e.png)

Here is the new option, similar to your original choice, which can search (auto-filter) & apply multiple tick-boxes
![image](https://cloud.githubusercontent.com/assets/21021038/25842765/62994da6-34cf-11e7-9de2-0c3447d19a6d.png)

To experience, please follow this link, at the 2nd drop-down: [](http://www.jqueryrain.com/?N8CC19tH)

Once you agree, we'll proceed.

**Comment by christa23** [comment]
Yes I agree.

**Comment by sancao** [comment]
i have finished this task,@christa23 could you review it then tell me what you would need to improve or change if any. Wish you have a good day.

**Comment by christa23** [comment]
The dev website does not allow me to sign up with zip code 85085 which is on the list.
![screen shot 2017-05-18 at 12 53 28 pm](https://cloud.githubusercontent.com/assets/11478530/26220822/138324e8-3bc9-11e7-9789-823bd9d6938a.png)

**Comment by sancao** [comment]
hi @christa this function work based on list companies registered in our app before, so if we have no companies serve in this zip code, no pool owners can register on this zip code. then the app will display the modal and require user input email to notify later. How do you think if you want to change? please explain.
